<Project>
  <PropertyGroup>
    <AssemblyName>ExcelSheetManager</AssemblyName>
    <IntermediateOutputPath>obj\Release\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>D:\Dev\Source Code\ExcelSheetManager\obj\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>ExcelSheetManager</_TargetAssemblyProjectName>
    <RootNamespace>ExcelSheetManager</RootNamespace>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ExcelDnaSetComServer>true</ExcelDnaSetComServer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ExcelDna.AddIn" Version="1.9.0" />
    <PackageReference Include="ExcelDna.Interop" Version="16.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.integration\1.9.0\lib\net462\ExcelDna.Integration.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\Microsoft.CSharp.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.interop\16.0.0\lib\net452\Microsoft.Office.Interop.Excel.dll">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </ReferencePath>
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.interop\16.0.0\lib\net452\Microsoft.Vbe.Interop.dll">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </ReferencePath>
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\mscorlib.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.interop\16.0.0\lib\net452\office.dll">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </ReferencePath>
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\PresentationCore.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\PresentationFramework.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Core.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Data.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Drawing.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Numerics.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Runtime.Serialization.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Windows.Forms.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Xaml.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Xml.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Xml.Linq.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationClient.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationClientsideProviders.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationProvider.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationTypes.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\WindowsBase.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\WindowsFormsIntegration.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="D:\Dev\Source Code\ExcelSheetManager\obj\Release\net48\Views\TaskPaneView.g.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>